### ISSUE TITLE
Strapi shows error(talking too long to respond) when starting dev server.

### ISSUE THREAD

**Issue by lambrohan** [MattieBelt/strapi-hook-algolia#5]
```
[2020-09-10T15:44:45.145Z] debug ⛔️ Server wasn't able to start properly.
[2020-09-10T15:44:45.146Z] error (hook: algolia) is taking too long to load.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

ps: 
I checked my internet connections if it's the problem but it seems not.
Also tried running it multiple times & it shows same errors every time.
I'm using Strapi v3.1.1

**Comment by MattieBelt** [comment]
Hey @lambrohan, thanks for using this package and for reporting this issue.
I do have some questions for you to give me more context.

- Did it work before?
- Machine info? (OS, node, npm)
- Which `strapi-hook-algolia` version are you using?

I will test it tomorrow.

**Comment by lambrohan** [comment]
Thanks for the reply man! It's a great package and very helpful.
System Info -
```
strapi-hook-algolia : 3.1.4
node v 12.17.0
yarn 1.22.4
windows 10 (1909 OS Build 18363.1082)
```

**Comment by MattieBelt** [comment]
Hey @lambrohan, I still have some further question to identify the bug, I tested it out on strapi `v3.1.4` and `v3.1.1` but didn't experience any error's on startup (using Ubuntu).

- Since when did it occur, did you make any changes, did it work before hand? 
- Could you test it out on a fresh project and provide me steps to reproduce?
- Could I maybe check your sources/snippets of your code to test it out?

The more detailed you are, the better I can help to fix it :wink:

**Comment by lambrohan** [comment]
Fixed it by upgrading my Strapi version from `3.1.1` to `3.1.4`
